### PR TITLE
test for existence of @_session.getCollectionView

### PR DESCRIPTION
**Pull request by SachaG**
I can't say I really understand how this package works, but hopefully that should at least prevent the error I've been getting (see https://github.com/peerlibrary/meteor-reactive-publish/issues/17)

### CODE REVIEW

**Comment by SachaG** [comment]
Any status update on this @mitar? It's not a big deal, but seeing random errors in the logs can be confusing or new Telescope users, so I'd love to get this fixed if possible :)

**Comment by mitar** [comment]
Sorry, life.

I hope I will get back to coding soon.

**Comment by SachaG** [comment]
I understand, keep me posted. I can also do it myself if you give me the rights.

**Comment by mitar** [comment]
I do not like this fix. It looks ... strange. Why would there be situation where `@_session.getCollectionView` does not exist?

**Comment by SachaG** [comment]
I don't know, but that error (see https://github.com/peerlibrary/meteor-reactive-publish/issues/17) definitely happens without the fix.

**Comment by mitar** [comment]
I finally have some time to look into this. As I mentioned, this just hides the underlying issue and does not really explain what is happening. So I will not merge this in.

**Pull request closed without merging**
